@startuml
actor Admin
left to right direction
rectangle "Digital Displayboard System" {
    Admin -- (Manage Posts)
    Admin -- (Manage Categories)
    Admin -- (View Dashboard)
    Admin -- (Search and Filter Content)
    Admin -- (View Statistics)
}
@enduml