
@startuml
left to right direction

actor Administrator

rectangle "Digital Displayboard System" {
    Administrator --> (Log in)
    Administrator --> (Create announcement)
    Administrator --> (Update announcement)
    Administrator --> (Delete announcement)
}
@enduml