@startuml
left to right direction
actor Admin

rectangle "Sprint 1: Display statistics"{
    Admin -- (View Dashboard for statistics)
    (View Dashboard for statistics) <.. (See Recent Posts) : <<extend>>
    (View Dashboard for statistics) <.. (View Post Statistics) : <<extend>>
    (View Dashboard for statistics) <.. (View Category Usage) : <<extend>>
    (View Dashboard for statistics) <.. (Posts, Users, Categories) : <<extend>>
}
@enduml
